### PR TITLE
Added validate option

### LINKED ISSUE #9: Add php:validate compile option

### PR DESCRIPTION
**Pull request by AlexeyKupershtokh**
Fixes #9.
Added support for php:validate thrift option.
```
  php (PHP):
    validate:        Generate PHP validator methods
```
I based branch this on the include-dirs since I need both of them and I suppose there's no reason to e.g. merge validate and not merge include-dirs.

### CODE REVIEW

**Comment by AlexeyKupershtokh** [comment]
With this option thrift additionally generates code snippets like this:
```diff
@@ -120,9 +136,16 @@ class TransactionsApplyResult extends TBase {
   }
 
   public function write($output) {
+    $this->_validateForWrite();
     return $this->_write('TransactionsApplyResult', self::$_TSPEC, $output);
   }
 
+  private function _validateForWrite() {
+    if ($this->profileState === null) {
+      throw new TProtocolException('Required field TransactionsApplyResult.profileState is unset!');
+    }
+  }
+
 }
```

**Comment by AlexeyKupershtokh** [comment]
Please also update documentation and unit tests for this feature too.

**Comment by xkobal** [comment]
Good point, I'm waiting before the include-dir correction before merge this ine

**Comment by AlexeyKupershtokh** [comment]
Actually I find this option even more useful to be turned on by default.
Maybe add default = true in the configuration and the command definition?

**Comment by xkobal** [comment]
I haven't tested it yet. Can you explain me the goal of the "php:validate" option ?

**Comment by AlexeyKupershtokh** [comment]
Without this option thrift generates php code that allows writing objects with missing required fields.
With this option enabled thrift adds checks for these fields in order to prevent sending such corrupted data. See an example diff I attached in the comment https://github.com/overblog/ThriftBundle/pull/10#issuecomment-126187212

**Comment by xkobal** [comment]
That's a good point, and something we need at Overblog. So you can enable it by default.

**Comment by AlexeyKupershtokh** [comment]
Done.
BTW, in my another package I have [separate tests for configuration](https://github.com/AlexeyKupershtokh/nginx_push_stream_bundle/tree/master/Tests/DependencyInjection).
Maybe you would like to do something similar in the ThriftBundle.

**Pull request merged**
